Make a videojs preset based on angular preset
videojs/conventional-changelog-videojs pull request #1
Opened 2016-10-04 23:08 UTC by gkatsev

The main difference is that it allows all of the known commit groups into the changelog. It then sorts them by BREAKING CHANGE, then Features, then Bug Fixes, finally following by each other commit group sorted by the group's title.

2016-10-04 23:09 UTC, gkatsev commented on index.js
> +  commitGroupsSort: function(group1, group2) {
Can't think of an easier way to bubble up things in order of:
Breaking, Features, Bug, {{title}}

2016-10-05 16:27 UTC, misteroneill requested changes

2016-10-05 16:27 UTC, misteroneill commented on index.js
> +    if (group1.title === 'Bux Fixes') {
Typo!

2016-10-05 16:27 UTC, misteroneill commented on index.js
> +  commitGroupsSort: function(group1, group2) {
What about:

```js
const titles = [
  'BREAKING CHANGES',
  'Features',
  'Bug Fixes'
];

for (let i = 0; i < titles.length; i++) {
  if (group1.title === titles[i]) {
    return -1;
  }
  if (group2.title === titles[i]) {
    return 1;
  }
}
```

2016-10-05 16:30 UTC, gkatsev commented on index.js
> +  commitGroupsSort: function(group1, group2) {
Yeah, looks like that would simplify it a bit.

2016-10-05 16:30 UTC, gkatsev commented on index.js
> +    if (group1.title === 'Bux Fixes') {
oops.

2016-10-05 18:00 UTC, imbcmdth commented on index.js
> +  commitGroupsSort: function(group1, group2) {
```
const titles = [
  'BREAKING CHANGES',
  'Features',
  'Bug Fixes'
];

return Math.sqrt(titles.indexOf(group1.title)) - Math.sqrt(titles.indexOf(group2.title));
```

2016-10-05 18:03 UTC, imbcmdth commented on index.js
> +  commitGroupsSort: function(group1, group2) {
Wait that's not it... so close!

2016-10-05 19:10 UTC, misteroneill commented on index.js
> +  commitGroupsSort: function(group1, group2) {
You're a madman @imbcmdth!

2016-10-05 19:15 UTC, gkatsev commented on index.js
> +  commitGroupsSort: function(group1, group2) {
I went with the loop approach.

2016-10-05 19:45 UTC, merged